defaultNamespaceSettings:
  name: defaultSettings
  annotations:
    default: annotation
  labels:
    default: label
  mode: upsert
namespaces: # Creates all  namespaces listed with the metadata specified
  - name: one
    annotations:
      foo: one
    labels:
      bar: one
    mode: sync # Deletes all existing add only those configured here
  - name: two
    annotations:
      foo: two
    labels:
      bar: two
    mode: insert # Inserts new only. Does not edit existing in case of conflict
  - name: three
    annotations:
      foo: three
      thisL: should
    labels:
      add: new
    mode: upsert # Inserts new, updates existing. Does not delete
  - name: four
